"""Pins the host's packages so an extension can never replace them.

An extension may depend on torch/diffusers/transformers but never install its own - two copies in
one process is a corrupted CUDA context, not a version skew.

The constraint file pins every installed distribution. A requirement needing a different version
fails to resolve, and that failure *is* the host-override signal.
"""

from __future__ import annotations

import hashlib
import importlib.metadata
import re
from dataclasses import dataclass
from pathlib import Path

from .paths import write_atomic

#: Packages an extension may never provide, even at the host's exact version. Anything here is
#: pruned from an extension's private site/ after install, so the finder cannot route it.
HOST_PROTECTED: frozenset[str] = frozenset(
    {
        "torch",
        "torchvision",
        "torchaudio",
        "torchao",
        "diffusers",
        "transformers",
        "accelerate",
        "safetensors",
        "tokenizers",
        "huggingface-hub",
        "numpy",
        "scipy",
        "fastapi",
        "uvicorn",
        "starlette",
        "pydantic",
        "pydantic-core",
        "psutil",
        "xfuser",
        "nvidia-ml-py",
        "inline-core",
    }
)

_NAME_RE = re.compile(r"^\s*([A-Za-z0-9][A-Za-z0-9._-]*)")


def canonical(name: str) -> str:
    """PEP 503 normalization, so ``Huggingface_Hub`` and ``huggingface-hub`` compare equal."""
    return re.sub(r"[-_.]+", "-", name).lower()


@dataclass(frozen=True)
class Conflict:
    """One dependency an extension wants that the host already owns at another version."""

    name: str
    host_version: str
    wanted: str

    @property
    def protected(self) -> bool:
        return canonical(self.name) in HOST_PROTECTED

    def message(self) -> str:
        if self.protected:
            return (
                f"{self.name} is part of the shared Inline runtime and cannot be replaced "
                f"(installed: {self.host_version}, extension wants: {self.wanted})"
            )
        return (
            f"{self.name} {self.wanted} conflicts with the installed {self.name} "
            f"{self.host_version}"
        )

    def to_json(self) -> dict[str, object]:
        return {
            "name": self.name,
            "hostVersion": self.host_version,
            "wanted": self.wanted,
            "protected": self.protected,
            "message": self.message(),
        }


def host_distributions() -> dict[str, str]:
    """Canonical name -> version for every distribution in the running interpreter."""
    found: dict[str, str] = {}
    for dist in importlib.metadata.distributions():
        name = dist.metadata["Name"] if dist.metadata else None
        if not name:
            continue  # a malformed dist-info in site-packages must not break installs
        version = dist.version
        if version:
            found[canonical(name)] = version
    return found


def fingerprint(host: dict[str, str] | None = None) -> str:
    """Digest of the host's package set, so the constraint file is regenerated after an upgrade."""
    dists = host if host is not None else host_distributions()
    payload = ";".join(f"{name}=={version}" for name, version in sorted(dists.items()))
    return hashlib.sha256(payload.encode()).hexdigest()[:16]


def render(host: dict[str, str] | None = None) -> str:
    dists = host if host is not None else host_distributions()
    lines = [
        "# Generated by Inline Core - do not edit.",
        "# Every package installed in the host interpreter, pinned. An extension that needs a",
        "# different version of any of these fails to resolve rather than silently replacing it.",
        f"# host-fingerprint: {fingerprint(dists)}",
    ]
    lines.extend(f"{name}=={version}" for name, version in sorted(dists.items()))
    return "\n".join(lines) + "\n"


def write_constraints(path: Path, host: dict[str, str] | None = None) -> Path:
    """Write the constraint file, refreshing it only when the host's packages changed."""
    dists = host if host is not None else host_distributions()
    wanted = fingerprint(dists)
    try:
        if f"# host-fingerprint: {wanted}" in path.read_text(encoding="utf-8"):
            return path
    except OSError:
        pass
    write_atomic(path, render(dists))
    return path


def requirement_name(requirement: str) -> str:
    """The distribution name from a PEP 508 requirement string, canonicalized."""
    head = requirement.split(";", 1)[0].split("@", 1)[0].strip()
    match = _NAME_RE.match(head)
    return canonical(match.group(1)) if match else ""


def protected_requirements(requirements: tuple[str, ...]) -> list[str]:
    """Requirements naming a host-protected package. Runs in the security scan, before any
    resolution, so listing ``torch`` is blocked outright rather than diagnosed later."""
    return [req for req in requirements if requirement_name(req) in HOST_PROTECTED]


def parse_lock(lock_text: str) -> dict[str, str]:
    """Canonical name -> version from a fully pinned ``uv pip compile`` lockfile."""
    pinned: dict[str, str] = {}
    for raw in lock_text.splitlines():
        line = raw.split("#", 1)[0].strip()
        if not line or line.startswith("-"):
            continue
        name, sep, version = line.partition("==")
        if not sep:
            continue
        cleaned = version.split(";", 1)[0].split("--", 1)[0].strip()
        if cleaned:
            pinned[canonical(name.strip())] = cleaned
    return pinned


def conflicts(lock_text: str, host: dict[str, str] | None = None) -> list[Conflict]:
    """Pinned packages in an unconstrained lock that disagree with the host. Run only after a
    constrained resolve failed, to name the culprit instead of dumping a resolver trace."""
    installed = host if host is not None else host_distributions()
    found: list[Conflict] = []
    for name, version in sorted(parse_lock(lock_text).items()):
        current = installed.get(name)
        if current is not None and current != version:
            found.append(Conflict(name=name, host_version=current, wanted=f"=={version}"))
    return found


def prunable(site_dists: dict[str, str], host: dict[str, str] | None = None) -> list[str]:
    """Private-site distributions that duplicate a host package. Constraints already pinned them to
    the host version, so removing them guarantees the finder can't route e.g. numpy privately."""
    installed = host if host is not None else host_distributions()
    return sorted(name for name in site_dists if name in installed or name in HOST_PROTECTED)
